### ISSUE TITLE
Fails to Run

### ISSUE THREAD

**Issue by rebeltaz** [djware/SmallTVProWeatherMap#1]
I am assuming that this would be "installed" as a cron job to start at boot up for best performance? Aside from that, though, I cannot get it to run. I edited the .py to reflect the IP of the SmallTV, the URL for the weather map, and installed imagio. The other three were already installed. 

```
$ pip install requests imageio Pillow requests_toolbelt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in /home/derek/.local/lib/python3.10/site-packages (2.31.0)
Collecting imageio
  Downloading imageio-2.34.2-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (9.0.1)
Requirement already satisfied: requests_toolbelt in /usr/lib/python3/dist-packages (0.9.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/derek/.local/lib/python3.10/site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/derek/.local/lib/python3.10/site-packages (from requests) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests) (2020.6.20)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from imageio) (1.24.2)
Downloading imageio-2.34.2-py3-none-any.whl (313 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 313.5/313.5 kB 499.4 kB/s eta 0:00:00
Installing collected packages: imageio
Successfully installed imageio-2.34.2

```

python is not available on my system (ubuntu 22.04). The package to install it is called 'python-is-python3', so... I am trying to start it with 

python3 weatertv.py

This is the output from that command. 

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests_toolbelt/_compat.py", line 48, in <module>
    from requests.packages.urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (/home/derek/.local/lib/python3.10/site-packages/urllib3/contrib/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/derek/Downloads/test/SmallTVProWeatherMap/weatertv.py", line 7, in <module>
    from requests_toolbelt.multipart.encoder import MultipartEncoder
  File "/usr/lib/python3/dist-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/usr/lib/python3/dist-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/usr/lib/python3/dist-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/usr/lib/python3/dist-packages/requests_toolbelt/_compat.py", line 50, in <module>
    from urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'urllib3.contrib' (/home/derek/.local/lib/python3.10/site-packages/urllib3/contrib/__init__.py)
```

**Comment by rebeltaz** [comment]
Nevermind. Apparently, I have to run it as sudo. Neat script. Thanks!
